In [1]:
import numpy as np


In [9]:
arr=np.array([1,5,4,8,6,3])

print("Array : ",arr)


#2d array
matrix=np.array([[1,2,3],[7,8,9],[4,5,6]])
print("\n",matrix)

print("\n",arr+2)#Add 2 in each element
print("\n",arr*2)#multiply by 2 in each element

#Generatng array of zeroes

zeroes=np.zeros((3,3))

print("\n",zeroes)

#Generating array of ones

ones=np.ones((3,3))
print("\n",ones)

#arrange within range
arranged=np.arange(0,10,2)
print("\n",arranged)



Array :  [1 5 4 8 6 3]

 [[1 2 3]
 [7 8 9]
 [4 5 6]]

 [ 3  7  6 10  8  5]

 [ 2 10  8 16 12  6]

 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 [0 2 4 6 8]


In [10]:
# Generating a random array
random_arr = np.random.rand(3, 3)  # 3x3 matrix with random values between 0 and 1
print(random_arr)

[[0.13296912 0.64030784 0.26687509]
 [0.68280099 0.03180628 0.39378395]
 [0.81958299 0.40234072 0.4964166 ]]


In [11]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1])   
print(arr[-1])  


matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix[1, 2]) 

arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[1:4]) 
print(arr[:3])  
print(arr[::2]) 



20
50
6
[20 30 40]
[10 20 30]
[10 30 50]


In [23]:
#Matrix operations

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A)

print("\n",A + B)  # Element-wise addition
print("\n",A * B)  # Element-wise multiplication
print("\n",np.dot(A, B))  # Matrix multiplication
print("\n",A.T)  # Transpose of a matrix


[[1 2]
 [3 4]]

 [[ 6  8]
 [10 12]]

 [[ 5 12]
 [21 32]]

 [[19 22]
 [43 50]]

 [[1 3]
 [2 4]]


In [21]:
arr = np.array([10, 20, 30, 40, 50,80])
reshaped = arr.reshape(2,3)
print(arr)
print(reshaped)

[10 20 30 40 50 80]
[[10 20 30]
 [40 50 80]]


In [16]:
#Statical functions

arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))   # Output: 3.0
print(np.median(arr)) # Output: 3.0
print(np.std(arr))    # Standard deviation
print(np.var(arr))    # Variance


3.0
3.0
1.4142135623730951
2.0


In [28]:
#Arr[layer, row, column] indexing

Arr=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

print(Arr)

print(Arr[0,1,2])

print("Shape:", Arr.shape)   # Output: (3, 3, 3)
print("Number of Dimensions:", Arr.ndim)  # Output: 3


[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
6
Shape: (3, 3, 3)
Number of Dimensions: 3
